### ISSUE TITLE
binaries?

### ISSUE THREAD

**Issue by CPernet** [tkkarjal/magia#101]
hello,

I wrote a 100% matlab ecat2nii (which I will share of course :-)) and wanted to compare with your code 

in [convert_ecat2nii](https://github.com/tkkarjal/magia/blob/master/convert_ecat2nii.m) on line 9 you call the cmd [imgflip](https://github.com/tkkarjal/magia/blob/master/convert_ecat2nii.m#L9) and then on line 13 [ecat2nii](https://github.com/tkkarjal/magia/blob/master/convert_ecat2nii.m#L9)  ; where did you get those binaries from? (is that in pet surfer?) - so I can compare with my conversion

thx

**Comment by joupes** [comment]
Hy Cyril, apologies for an awfully late response. The binaries are from tpclib (https://gitlab.utu.fi/vesoik/tpcclib).
