### ISSUE TITLE
A question about impicit masks in Logan fit

### ISSUE THREAD

**Issue by SoodehMoallemian** [tkkarjal/magia#102]
Hi all,

For technical reasons we are using only `magia_logan_image.m` function, mainly because we use reference region instead of blood sampling as the input function. 

We also use Ecat HR+ with fbp reconstruction, which leads to a lot of negative values and NANs in first frames.
In `magia_logan_image.m` function, you apply a mask filtering the negative, 0s and NANs, which is too strict for us, removing almost all image. Unfortunately we can't share the images for confidentiality.
 
For us, we see two solutions:
1. feed only frames after `t*`, but it will reduce the values of your `Y` variable, we guess it should not affect `Vt` but will reduce intercept
2. Use `magia_fit_logan.m` directly, applying only our pre-calculated brain mask.

Could you suggest the best way to proceed, please?

Thanks,
Soodeh

**Comment by joupes** [comment]
Hi, sorry for very late response! I'd suggest the second option.
