### ISSUE TITLE
Always calculate parametric images before spatial normalization

### ISSUE THREAD

**Issue by tkkarjal** [tkkarjal/magia#19]
For example, in branch # 5 the PET image is first spatially normalised, and only after that are the parametric images calculated. Reversing the order would

1) Provide native space parametric images
2) Speed up the process because in native space there are fewer voxels in which the modelling needs to be done

**Comment by tkkarjal** [comment]
Parametric images are now always calculated before spatial normalization.

**Comment by colddie** [comment]
Just curious how can I find the images in the output folder. I only saw the ones after normalization.
