### ISSUE TITLE
get_frames_dcm

### ISSUE THREAD

**Issue by buccimtpc** [tkkarjal/magia#24]
Hi, maybe get_frames_dcm should be in the magia repository.
I was trying to branching out to edit line 7
gunzip -fr
instead of
gunzip -r

with 'f' it forces the overwrite otherwise you have to manually say 'y' to each overwrite.

if you have gunzip -r somewhere else you should think about changing the other instances too ;)

**Comment by tkkarjal** [comment]
I have not included get_frames_dcm because it's not really a function of magia but rather something generally useful. Maybe we should create a new GitHub project for such functions?

**Comment by tkkarjal** [comment]
Ended up not implementing the requested change.
