### ISSUE TITLE
Feature request: Save ROI volumes 

### ISSUE THREAD

**Issue by eebrown** [tkkarjal/magia#34]
Please consider whether it would be useful to save the ROI volumes with the output time activity curves. This would mean the ROIs could be later merged into a larger ROI, which is helpful when different analyses are planned. Then an option to save the TACs from all of the atlas ROIs could be chosen for flexibility down the road.

Relatedly, I am working on an R package for tac analysis (that calculates such weighted average TACs) and have added support for the magia tac output .mat file (https://github.com/eebrown/PET/tree/devel).

**Comment by tkkarjal** [comment]
Thanks. It's a useful idea. I will think of a way to implement this.

**Comment by tkkarjal** [comment]
The ROI volumes are now written to disk in the file tacs.mat
