### ISSUE TITLE
magia_read_specs.m saves numeric values as char

### ISSUE THREAD

**Issue by eebrown** [tkkarjal/magia#48]
The function `magia_read_specs(specs_file)` in `magia_read_specs.m` stores numeric values from the text file as char. This causes problems, such as `'0'` being evaluated as true, where `0` should be false, e.g. in `magia_processor.m`. I think the frames are also loaded as `char` and not converted to the expected format.

**Comment by tkkarjal** [comment]
Thanks! I made a quick fix for this one. The parameter mc_excluded_frames may still cause some problems, but I will get into that later.

**Comment by eebrown** [comment]
Thanks, the fix works.
