### ISSUE TITLE
Important: PET-template-based spatial normalization ('old normalize') problem

### ISSUE THREAD

**Issue by tkkarjal** [tkkarjal/magia#88]
Using [11C]raclopride data I noticed that the process of warping the standardized radioactivity template to an individual's mean-PET image is highly unstable. Two Magia-runs with identical settings can lead to dramatically different BP estimates (e.g. in putamen 4 vs. 1). On the other hand the warpings from the individual to the template work much more reliably.

The process needs to be changed. If PET-based spatial normalization is used, then the ROIs should not be warped from the MNI space to the individual space. Instead, the individual PET images should be warped to MNI space.

**Comment by tkkarjal** [comment]
I created a new branch for this

**Comment by colddie** [comment]
Is this problem solved?

**Comment by tkkarjal** [comment]
Yes, the problem has been solved. Thanks for asking.
